"""Disk monitoring module."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/monitors/disk.ipynb.

# %% auto 0
__all__ = ['get_disk_info']

# %% ../../nbs/monitors/disk.ipynb 3
import psutil

# %% ../../nbs/monitors/disk.ipynb 5
def get_disk_info():
    """Get disk usage information."""
    partitions = psutil.disk_partitions()
    disk_info = []

    for partition in partitions:
        try:
            usage = psutil.disk_usage(partition.mountpoint)
            disk_info.append({
                'device': partition.device,
                'mountpoint': partition.mountpoint,
                'fstype': partition.fstype,
                'total': usage.total,
                'used': usage.used,
                'free': usage.free,
                'percent': usage.percent
            })
        except PermissionError:
            continue

    return disk_info
